### ISSUE TITLE
C string conversion

### ISSUE THREAD

**Issue by wilsonjord** [aferust/opencvd#10]
```d
imwrite(format("optflow%d.png",1), img); // stange filename or error
imwrite(format("optflow%d.png\0",1), img); // correct filename
imwrite(format("optflow%d.png",1).toStringz, img); // does not compile
```

Would an overload accepting char* be suitable?

**Comment by aferust** [comment]
I have pushed those overloads. Pull and compile again. Please let me know if it compiles because I have no time to test it right now.

**Comment by wilsonjord** [comment]
Compiles and works as expected, thanks!
