### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by trikko** [aferust/opencvd#6]
I wonder if I missed something but this syntax is pretty tedious:

```d
int[] params = [1 /*IMWRITE_JPEG_QUALITY*/, 95];
encoded = imencodeWithParams(".jpg", image, IntVector(params.ptr, params.length.to!int));
```

I would add some helpers function like ```intVector``` (or simply "vector" if templatized) to add a bit of syntax sugar:

```d
auto intVector(int[] data) { return IntVector(data.ptr, data.length.to!int); }
// ... code above becomes:
encoded = imencodeWithParams(".jpg", image, params.intVector);
```

The same goes for ```ByteArray```, etc... 

Side questions:
- Why those functions don't accept ```int[]``` instead of ```intVector```?
- Why some consts are missing (e.g.: IMWRITE_JPEG_QUALITY)?

**Comment by aferust** [comment]
OpenCV is a huge library, and it needs more hand and time to make the wrapper more d-idiomatic. I thought I wrapped all those intermediate types between c and d such as IntVector. It is obvious that I missed or ignore some functionalty. In the begining, I was just copying and pasting the things. Those are result of my hurrying to get the things done. We can easily do function overloading on d side of the code. Now, I am handling it.

**Comment by trikko** [comment]
Anyway very nice library, it works fine for me as it is now!

**Comment by aferust** [comment]
Thank you for it.
