### ISSUE TITLE
Confused about the build process on Windows

### ISSUE THREAD

**Issue by AndrejMitrovic** [aferust/opencvd#7]
Hi,

I've built `opencv` on Win10, but I'm having trouble following the instructions on https://github.com/aferust/opencvd#windows-10-64-bit for building `opencvd`.

Specifically:

```
cd into opencvd/c/, create a build folder, and run cmake:
cd opencvd/c
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64"
```

There are no cmake files in the `opencvd` repo, so this errors with ` "C:/dev/opencvd" does not appear to contain CMakeLists.txt.`. 

Are these instructions outdated / should we just use `dub` now?

Thanks!

**Comment by aferust** [comment]
There is a CMakeLists.txt in opencvd/c/.
Dub is not enough sorry. You have to compile the cpp files using cmake.
Are you sure that you are running `cmake .. -G "Visual Studio 15 2017 Win64"` inside `opencvd/c/build`?

**Comment by AndrejMitrovic** [comment]
Ah I was running it in `opcnvd/c/` instead of the build directory. Apologies! And thanks!
